### ISSUE TITLE
Are there any updates planned to support M1 chips ?

### ISSUE THREAD

**Issue by hjnnjh** [pytorch/functorch#819] opened 2022-05-19 08:13 UTC

**Comment by zou3519** [comment] 2022-05-19 19:32
We can add it to the roadmap. It's possible that this already works but we have not tried it yet.

**Comment by vfdev-5** [comment] 2022-05-19 21:00
@hjnnjh you can try install pytorch nightly following https://pytorch.org/get-started/locally/ on your M1 and then compile functorch from source:
```bash
pip install git+https://github.com/pytorch/functorch
```

Just few days ago it was an announcement about "Introducing Accelerated PyTorch Training on Mac": https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/

> Until now, PyTorch training on Mac only leveraged the CPU, but with the upcoming PyTorch v1.12 release, developers and researchers can take advantage of Apple silicon GPUs for significantly faster model training. This unlocks the ability to perform machine learning workflows like prototyping and fine-tuning locally, right on Mac.

**Comment by vfdev-5** [comment] 2022-05-24 18:32
@sirykd thanks for reporting. Do you experience any issues with torch 1.13.0.dev20220524 on M1 ?

**Comment by ludwigwinkler** [comment] 2022-06-29 09:03
I'm running the ARM conda, which was described as a prerequisite to run PyTorch with the Apple MPS acceleration. For me, building from source results in an error during the building of the wheels.

Is there any recommendation as to how to get functorch running on ARM conda on PyTorch 1.12?

**Comment by ludwigwinkler** [comment] 2022-06-29 10:19
@vfdev-5 , thank you for the hint. It worked.

For anybody else with the same problem for ARM64 conda, Apple Silicon, PyTorch 1.12:
pip install --user git+https://github.com/pytorch/functorch@release/0.2

**Comment by sirykd** [comment] 2022-06-29 10:55
> @sirykd thanks for reporting. Do you experience any issues with torch 1.13.0.dev20220524 on M1 ?

Sorry for the late response. I had some during the short initial testing a month ago, but haven't tested any further since then.

**Comment by vfdev-5** [comment] 2022-07-13 13:45
@nicolas-dufour I think it should be already suppored. Otherwise can you please try pytorch nightly and install functorch from source ?

**Comment by nicolas-dufour** [comment] 2022-07-13 14:21
@vfdev-5  I've just made an install with clean conda env.
Installed only torch with conda install pytorch torchvision cpuonly -c pytorch-nightly
and functorch with pip install --user "git+https://github.com/pytorch/functorch.git" and i still get the exact same error

**Comment by vfdev-5** [comment] 2022-07-13 14:44
Thanks for the logs, let me check that

**Comment by vfdev-5** [comment] 2022-07-13 15:37
Just for visibility, I run some tests (vmap, eager_transforms and ops) on M1 12.3 CI machine: https://github.com/pytorch/functorch/runs/7324211885?check_suite_focus=true (it fails but with a value error)
Here is env log:
```
PyTorch version: 1.13.0.dev20220713
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A
OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.19.20201117-gb803813
Libc version: N/A
Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] functorch==0.3.0a0+cdfaa03
[pip3] numpy==1.23.1
[pip3] torch==1.13.0.dev20220713
[pip3] torchvision==0.14.0.dev20220713
[conda] functorch                 0.3.0a0+cdfaa03           dev_0    <develop>
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220713          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220713          pypi_0    pypi
```

@nicolas-dufour could you please confirm that you experience the same issue with torch installed from pypi ?

**Comment by nicolas-dufour** [comment] 2022-07-13 16:42
@vfdev-5 Still the RuntimeError on my side installing with pip

**Comment by vfdev-5** [comment] 2022-07-13 16:59
@nicolas-dufour I suspect that this may also be an issue with clang 13.0.0. We had some similar macosx m1 related issues on torchvision: 
- https://github.com/pytorch/vision/pull/6152#issuecomment-1152748417
- https://github.com/pytorch/pytorch/issues/79421

If you have a possibility to upgrade your clang to 13.1.X and check that it would be great.

**Comment by nicolas-dufour** [comment] 2022-07-13 17:08
With the updated clang, i cannot install functorch anymore. I get the following error:
```
Collecting git+https://github.com/pytorch/functorch.git
  Cloning https://github.com/pytorch/functorch.git to /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/functorch.git /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj
  Resolved https://github.com/pytorch/functorch.git to commit d40a4963213faf05855ae634bf84b3412572f337
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.13.0.dev in /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages (from functorch==0.3.0a0+d40a496) (1.13.0.dev20220713)
Requirement already satisfied: typing-extensions in /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages (from torch>=1.13.0.dev->functorch==0.3.0a0+d40a496) (4.3.0)
Building wheels for collected packages: functorch
  Building wheel for functorch (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      Building wheel functorch-0.3.0a0+d40a496
      running bdist_wheel
      /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-3.9
      creating build/lib.macosx-11.1-arm64-3.9/functorch
      copying functorch/version.py -> build/lib.macosx-11.1-arm64-3.9/functorch
      copying functorch/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch
      creating build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      copying functorch/experimental/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      copying functorch/experimental/batch_norm_replacement.py -> build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      creating build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/partitioners.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/compile_utils.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/named_members_polyfill.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/config.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/decompositions.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/python_key.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/pytree_hacks.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/top_operators_github_usage.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/custom_function.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/fx_minifier.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/monkey_patching.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/aot_autograd.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/compilers.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/eager_transforms.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/vmap.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/benchmark_utils.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/make_functional.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      creating build/lib.macosx-11.1-arm64-3.9/functorch/compile
      copying functorch/compile/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/compile
      running build_ext
      building 'functorch._C' extension
      creating build/temp.macosx-11.1-arm64-3.9
      creating build/temp.macosx-11.1-arm64-3.9/private
      creating build/temp.macosx-11.1-arm64-3.9/private/var
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ndufour/anaconda3/envs/test_functorch/include -arch arm64 -I/Users/ndufour/anaconda3/envs/test_functorch/include -fPIC -O2 -isystem /Users/ndufour/anaconda3/envs/test_functorch/include -arch arm64 -DFUNCTORCH_BUILD_MAIN_LIB -I/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/TH -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/THC -I/Users/ndufour/anaconda3/envs/test_functorch/include/python3.9 -c /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.cpp -o build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.o -O3 -std=c++14 -fdiagnostics-color=always -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.cpp:1:
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.h:2:
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/Interpreter.h:4:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/c10/util/variant.h:223:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/exception:83:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/cstdlib:85:
      /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/stdlib.h:93:15: fatal error: 'stdlib.h' file not found
      #include_next <stdlib.h>
                    ^~~~~~~~~~
      1 error generated.
      error: command '/Users/ndufour/anaconda3/envs/test_functorch/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for functorch
  Running setup.py clean for functorch
Failed to build functorch
Installing collected packages: functorch
  Running setup.py install for functorch ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for functorch did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      Building wheel functorch-0.3.0a0+d40a496
      running install
      /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-3.9
      creating build/lib.macosx-11.1-arm64-3.9/functorch
      copying functorch/version.py -> build/lib.macosx-11.1-arm64-3.9/functorch
      copying functorch/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch
      creating build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      copying functorch/experimental/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      copying functorch/experimental/batch_norm_replacement.py -> build/lib.macosx-11.1-arm64-3.9/functorch/experimental
      creating build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/partitioners.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/compile_utils.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/named_members_polyfill.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/config.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/decompositions.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/python_key.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/pytree_hacks.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/top_operators_github_usage.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/custom_function.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/fx_minifier.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/monkey_patching.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/aot_autograd.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/compilers.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/eager_transforms.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/vmap.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/benchmark_utils.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      copying functorch/_src/make_functional.py -> build/lib.macosx-11.1-arm64-3.9/functorch/_src
      creating build/lib.macosx-11.1-arm64-3.9/functorch/compile
      copying functorch/compile/__init__.py -> build/lib.macosx-11.1-arm64-3.9/functorch/compile
      running build_ext
      /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      building 'functorch._C' extension
      creating build/temp.macosx-11.1-arm64-3.9
      creating build/temp.macosx-11.1-arm64-3.9/private
      creating build/temp.macosx-11.1-arm64-3.9/private/var
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch
      creating build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ndufour/anaconda3/envs/test_functorch/include -arch arm64 -I/Users/ndufour/anaconda3/envs/test_functorch/include -fPIC -O2 -isystem /Users/ndufour/anaconda3/envs/test_functorch/include -arch arm64 -DFUNCTORCH_BUILD_MAIN_LIB -I/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/TH -I/Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/THC -I/Users/ndufour/anaconda3/envs/test_functorch/include/python3.9 -c /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.cpp -o build/temp.macosx-11.1-arm64-3.9/private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.o -O3 -std=c++14 -fdiagnostics-color=always -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.cpp:1:
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/ADInterpreters.h:2:
      In file included from /private/var/folders/fn/c72nxv0x0xj4bzdgq3b0r86r0000gn/T/pip-req-build-amsk87tj/functorch/csrc/Interpreter.h:4:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/lib/python3.9/site-packages/torch/include/c10/util/variant.h:223:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/exception:83:
      In file included from /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/cstdlib:85:
      /Users/ndufour/anaconda3/envs/test_functorch/bin/../include/c++/v1/stdlib.h:93:15: fatal error: 'stdlib.h' file not found
      #include_next <stdlib.h>
                    ^~~~~~~~~~
      1 error generated.
      error: command '/Users/ndufour/anaconda3/envs/test_functorch/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> functorch

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by vfdev-5** [comment] 2022-07-13 17:18
I see, this looks a bit strange though as error. Here is the sequence of installation steps that worked for torchvision:
```
conda install -y -c conda-forge clang==14.0.4
python3 -mpip install --pre torch --extra-index-url=https://download.pytorch.org/whl/nightly
python3 setup.py develop
```
based on https://github.com/pytorch/vision/pull/6152/files

**Comment by vfdev-5** [comment] 2022-07-13 17:30
Thanks for checking that! Your another M1 Pro computer has same Clang version: 13.0.0 ?

**Comment by nicolas-dufour** [comment] 2022-07-14 09:08
Hi, it's someone else machine, i asked them to run the test for me but i think its 14.0.4
The error they get is the install error (not the runtimerror)

**Comment by nicolas-dufour** [comment] 2022-07-19 10:13
Hey @vfdev-5. I've reinstalled functorch from git with recent commits and it nows solved my pb. Thanks for the help!

**Comment by vfdev-5** [comment] 2022-07-19 10:27
@nicolas-dufour glad that it works. Which clang version you are using finally: 13.0.0 or another one ?

**Comment by nicolas-dufour** [comment] 2022-07-19 11:30
clang = 13.1.6

**Comment by hjnnjh** [comment] 2022-07-19 11:32
> > @hjnnjh you can try install pytorch nightly following https://pytorch.org/get-started/locally/ on your M1 and then compile functorch from source:
> > ```shell
> > pip install git+https://github.com/pytorch/functorch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just few days ago it was an announcement about "Introducing Accelerated PyTorch Training on Mac": https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/
> 
> Currently, the following happens even for the sanity checks from colab:
> 
> Example	Output
> ```python
> import torch
> from functorch import vmap
> 
> x = torch.randn(3)
> y = vmap(torch.sin)(x)
> assert torch.allclose(y, x.sin())
> ```
> 
> ```
> Traceback (most recent call last):
>   ...
>     y = vmap(torch.sin)(x)
>   File "/Users/sirykd/.local/lib/python3.9/site-packages/functorch/_src/vmap.py", line 365, in wrapped
>     batched_outputs = func(*batched_inputs, **kwargs)
> RuntimeError: batched == nullptr INTERNAL ASSERT FAILED at "/private/var/folders/_0/lckltx796z34m6jcvqkmlsnw0000gn/T/pip-req-build-pf4l763m/functorch/csrc/Interpreter.cpp":81, please report a bug to PyTorch. 
> ```
> 
> ```python
> import torch
> from functorch import grad
> 
> x = torch.randn([])
> y = grad(torch.sin)(x)
> assert torch.allclose(y, x.cos())
> ```
> 
> ```
> Traceback (most recent call last):
>   ...
>     y = grad(torch.sin)(x)
>   File "/Users/sirykd/.local/lib/python3.9/site-packages/functorch/_src/eager_transforms.py", line 1192, in wrapper
>     results = grad_and_value(func, argnums, has_aux=has_aux)(*args, **kwargs)
>   File "/Users/sirykd/.local/lib/python3.9/site-packages/functorch/_src/eager_transforms.py", line 1062, in wrapper
>     output = func(*args, **kwargs)
> NotImplementedError: Could not run 'aten::sin' with arguments from the 'UNKNOWN_TENSOR_TYPE_ID' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::sin' is only available for these backends: [Dense, FPGA, ORT, Vulkan, Metal, Meta, Quantized, CustomRNGKeyId, MkldnnCPU, Sparse, SparseCsrCPU, SparseCsrCUDA, NestedTensor, BackendSelect, Python, Fake, Named, Conjugate, Negative, ZeroTensor, FuncTorchDynamicLayerBackMode, ADInplaceOrView, AutogradOther, AutogradFunctionality, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, Autocast, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, Functionalize, DeferredInit, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, TESTING_ONLY_GenericWrapper, TESTING_ONLY_GenericMode, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, CPU, CUDA, HIP, XLA, MPS, IPU, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].
> 
> Undefined: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:29545 [default backend kernel]
> CPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCPU.cpp:37386 [kernel]
> CUDA: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:29545 [default backend kernel]
> HIP: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:29545 [default backend kernel]
> XLA: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:29545 [default backend kernel]
> MPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMPS.cpp:24666 [kernel]
> ...
> ```
> 
> Environment:
> 
> * MBA M1 (macOS 12.4)
> * torch 1.13.0.dev20220524
> * functorch 0.3.0a0+76976db

I have already installed functorch on my M1 Pro Macbook Pro successfully. Thank you!

**Comment by vfdev-5** [comment] 2022-07-19 11:35
As the problem is solved for everyone, let's close this issue (we can reopen it if problem persists).

**Closed by vfdev-5** 2022-07-19 11:35 UTC
Labels: high priority
